// Import the connection to the database
const database = require('../database/index');

const listarColetas = (req, res) => {
    const sql = 'SELECT * FROM coletas';

    // Execute the query to get the rows, returning all collections from the database
    database.all(sql, [], (err, rows) => {
        if (err) {
            return res.status(500).json({ erro: err.message });
        } 
        res.json(rows);
    })
}

const criarColeta = (req, res) => {
    // Destructuring: extract specific data from the request body
    const { solicitante_nome, solicitante_contato, endereco, tipo_material } = req.body

    // Simple validation (Clean Code: Fail Fast)
    if (!solicitante_nome || !endereco) {
        return res.status(400).json({ messagem: 'Nome e endereço são obrigatórios.' })
    }

    const sql = `INSERT INTO coletas (solicitante_nome, solicitante_contato, endereco, tipo_material, status) VALUES (?, ?, ?, ?, ?)`;

    // 'pendente' is the default status for new collections
    const params = [solicitante_nome, solicitante_contato, endereco, tipo_material, 'pendente'];
    
    // Execute the insert query in the database
    database.run(sql, params, function(err) {
        if (err) {
            return res.status(500).json({ erro: err.message });
        }

        // Success! this.lastID gets the ID automatically generated by SQLite
        res.status(201).json({
            id: this.lastID,
            solicitante_nome,
            solicitante_contato,
            endereco,
            tipo_material,
            status: 'pendente'
        });
    });
}

const atualizarColeta = (req, res) => {
    const { id } = req.params; // Gets the ID from the URL (ex: /coletas/1)
    const { status } = req.body; // Gets the new status from the JSON body

    const sql = `UPDATE coletas SET status = ? WHERE id = ?`;

    database.run(sql, [status, id], function(err) {
        if (err) {
            return res.status(500).json({ erro: err.message });
        }

        // Check if any row was changed
        if (this.changes === 0) {
            return res.status(404).json({ mensagem: 'Coleta não encontrada '});
        }

        res.json({ mensagem: 'Coleta atualizada com sucesso!', id, status });
    });
}

const deletarColeta = (req, res) => {
    const { id } = req.params;

    const sql = 'DELETE FROM coletas WHERE id = ?';

    database.run(sql, [id], function(err) {
        if (err) {
            return res.status(500).json({ erro: err.message });
        }

        if (this.changes === 0) {
            return res.status(404).json({ mensagem: 'Coleta não encontrada!' })
        }

        res.json({ mensagem: 'Coleta excluída com sucesso!' });
    });
}

module.exports = { listarColetas, criarColeta, atualizarColeta, deletarColeta };
